# Generated by Django 4.2.4 on 2023-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stock_date_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='last_updated',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
