# Generated by Django 4.2.4 on 2023-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_stockhistory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
